[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=830c3df1-4e8f-4a10-a972-37176043b2c6
Description=自走其_自动备份_自动备份
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
Delay 500

MoveTo 296,291
LeftClick 1 
Delay 10

MoveTo 797,291
LeftClick 1 
Delay 10


MoveTo 1548,576 
LeftClick 1 
Delay 10

MoveTo 794,793
LeftClick 1 
Delay 10
